/*********************************************************************
 * @file        APPACT_ConfigPublic.h
 * @brief       Template_BriefDescription.
 * @note        TemplateDetailsDescription.\n
 *
 * @author      xxxxxx
 * @date        jj/mm/yyyy
 * @version     1.0
 */
  
#ifndef APPSIG_CONFIGPUBLIC_H_INCLUDED
#define APPSIG_CONFIGPUBLIC_H_INCLUDED

    // ********************************************************************
    // *                      Includes
    // ********************************************************************
    #include "TypeCommon.h"
    // ********************************************************************
    // *                      Defines
    // ********************************************************************
    ///@brief Number maximum of max subsriber a SIGNAL can have 
    #define APPSIG_SIG_RCV_SUBSRIBERS_MAX   ((t_uint8)1)
    ///@brief Number maximum of max subsriber a MSG can have 
    #define APPSIG_MSG_RCV_SUBSRIBERS_MAX   ((t_uint8)1)
    // ********************************************************************
    // *                      Types
    // ********************************************************************
    ///@brief ENum for Signal Encoding
    typedef enum 
    {
        APPSIG_SIG_ENCODE_INTEL = 0,
        APPSIG_SIG_ENCODE_MOTOROLA,

        APPSIG_SIG_ENCODE_NB
    } t_eAPPSIG_SigEncode;
    ///@brief Enum to know where come from the signal 
    typedef enum 
    {
        APPSIG_MSG_ORIGIN_CAN = 0,
        APPSIG_MSG_ORIGIN_SRL,

        APPSIG_MSG_ORIGIN_NB
    } t_eAPPSIG_MsgOrigin;

    ///@brief Enum to know the direction of the message
    typedef enum 
    {
        APPSIG_MSG_DIR_RX = 0,          //---- msg is expected to be receive ----//
        APPSIG_MSG_DIR_TX,              //---- msg is expected to be send and received ----//
        APPSIG_MSG_DIR_RX_TX,           //---- msg is expected to receive and transmitted ----//
        APPSIG_MSG_DIR_UNUSED,          //---- msg is not used in this configuration ----//

        APPSIG_MSG_DIR_NB
    } t_eAPPSIG_MsgDirection;

    /* CAUTION : Automatic generated code section for Enum: Start */
    /**
    * @brief Signal list available.
    */
    typedef enum
    {
        APPSIG_SIGNAL_FMKCPU_MODSTATE = 0,
        APPSIG_SIGNAL_FMKCDA_MODSTATE,
        APPSIG_SIGNAL_FMKSRL_MODSTATE,
        APPSIG_SIGNAL_FMKFDCAN_MODSTATE,
        APPSIG_SIGNAL_FMKIO_MODSTATE,
        APPSIG_SIGNAL_FMKHRT_MODSTATE,
        APPSIG_SIGNAL_FMKTIM_MODSTATE,
        APPSIG_SIGNAL_APPSIG_MODSTATE,
        APPSIG_SIGNAL_APPSYS_MODSTATE,
        APPSIG_SIGNAL_APPSNS_MODSTATE,
        APPSIG_SIGNAL_APPACT_MODSTATE,
        APPSIG_SIGNAL_APPLGC_MODSTATE,
        APPSIG_SIGNAL_APPSDM_MODSTATE,
        APPSIG_SIGNAL_APPSPM_MODSTATE,
        APPSIG_SIGNAL_CYCLIC_DURATION,
        APPSIG_SIGNAL_SDM_DIAG_ITEM,
        APPSIG_SIGNAL_SDM_DIAG_REPORT_STATUS,
        APPSIG_SIGNAL_SDM_DIAG_DEBUG_INFO_1,
        APPSIG_SIGNAL_SDM_DIAG_DEBUG_INFO_2,
        APPSIG_SIGNAL_SDM_DIAG_ECU_SAFETY_ITEM,
        APPSIG_SIGNAL_SDM_DIAG_ECU_SAFETY_REPORT_STATUS,
        APPSIG_SIGNAL_SDM_DIAG_ECU_SAFETY_DEBUG_INFO_1,
        APPSIG_SIGNAL_SDM_DIAG_ECU_SAFETY_DEBUG_INFO_2,
        APPSIG_SIGNAL_FASTTASKDURATION,
        APPSIG_SIGNAL_SNS_ECDR_XL_POS,
        APPSIG_SIGNAL_SNS_ECDR_XL_SPD,
        APPSIG_SIGNAL_SNS_ECDR_XR_POS,
        APPSIG_SIGNAL_SNS_ECDR_XR_SPD,
        APPSIG_SIGNAL_SNS_ECDR_Y_POS,
        APPSIG_SIGNAL_SNS_ECDR_Y_SPD,
        APPSIG_SIGNAL_SNS_ECDR_Z_POS,
        APPSIG_SIGNAL_SNS_ECDR_Z_SPD,
        APPSIG_SIGNAL_SNS_ECDR_WHL_AV_L_POS,
        APPSIG_SIGNAL_SNS_ECDR_WHL_AV_L_SPD,
        APPSIG_SIGNAL_SNS_ECDR_WHL_AV_R_POS,
        APPSIG_SIGNAL_SNS_ECDR_WHL_AV_R_SPD,
        APPSIG_SIGNAL_SNS_ECDR_HD_KNF_POS,
        APPSIG_SIGNAL_SNS_ECDR_HD_KNF_SPD,
        APPSIG_SIGNAL_SNS_ECDR_HD_CNTR_KNF_POS,
        APPSIG_SIGNAL_SNS_ECDR_HD_CNTR_KNF_SPD,
        APPSIG_SIGNAL_SNS_ECDR_HD_HOLD_POS,
        APPSIG_SIGNAL_SNS_ECDR_HD_HOLD_SPD,
        APPSIG_SIGNAL_SNS_HD_UP_LEFT_DIST,
        APPSIG_SIGNAL_SNS_HD_DWN_LEFT_DIST,
        APPSIG_SIGNAL_SNS_HD_UP_RIGHT_DIST,
        APPSIG_SIGNAL_SNS_HD_DWN_RIGHT_DIST,
        APPSIG_SIGNAL_SNS_TRQ_MTR_XL_TRQ,
        APPSIG_SIGNAL_SNS_TRQ_MTR_XR_TRQ,
        APPSIG_SIGNAL_SNS_TRQ_MTR_Y_TRQ,
        APPSIG_SIGNAL_SNS_TRQ_MTR_Z_TRQ,
        APPSIG_SIGNAL_SNS_TRQ_MTR_WHL_AV_L_TRQ,
        APPSIG_SIGNAL_SNS_TRQ_MTR_WHL_AV_R_TRQ,
        APPSIG_SIGNAL_SNS_TRQ_MTR_HD_KNF_TRQ,
        APPSIG_SIGNAL_SNS_TRQ_MTR_CNTR_KNF_TRQ,
        APPSIG_SIGNAL_SNS_TRQ_MTR_HD_HOLD_TRQ,
        APPSIG_SIGNAL_ACT_SET_MTR_XL_PLS,
        APPSIG_SIGNAL_ACT_SET_MTR_XL_SPD,
        APPSIG_SIGNAL_ACT_SET_MTR_XL_TRG,
        APPSIG_SIGNAL_ACT_SET_MTR_XR_PLS,
        APPSIG_SIGNAL_ACT_SET_MTR_XR_SPD,
        APPSIG_SIGNAL_ACT_SET_MTR_XR_TRG,
        APPSIG_SIGNAL_ACT_SET_MTR_Y_PLS,
        APPSIG_SIGNAL_ACT_SET_MTR_Y_SPD,
        APPSIG_SIGNAL_ACT_SET_MTR_Y_TRG,
        APPSIG_SIGNAL_ACT_SET_MTR_Z_PLS,
        APPSIG_SIGNAL_ACT_SET_MTR_Z_SPD,
        APPSIG_SIGNAL_ACT_SET_MTR_Z_TRG,
        APPSIG_SIGNAL_ACT_SET_MTR_HD_KNF_PLS,
        APPSIG_SIGNAL_ACT_SET_MTR_HD_KNF_SPD,
        APPSIG_SIGNAL_ACT_SET_MTR_HD_KNF_TRG,
        APPSIG_SIGNAL_ACT_SET_MTR_HD_CNTR_KNF_PLS,
        APPSIG_SIGNAL_ACT_SET_MTR_HD_CNTR_KNF_SPD,
        APPSIG_SIGNAL_ACT_SET_MTR_HD_CNTR_KNF_TRG,
        APPSIG_SIGNAL_ACT_SET_MTR_HD_HOLD_PLS,
        APPSIG_SIGNAL_ACT_SET_MTR_HD_HOLD_SPD,
        APPSIG_SIGNAL_ACT_SET_MTR_HD_HOLD_TRG,
        APPSIG_SIGNAL_ACT_SET_MTR_WHL_AV_L_PLS,
        APPSIG_SIGNAL_ACT_SET_MTR_WHL_AV_L_SPD,
        APPSIG_SIGNAL_ACT_SET_MTR_WHL_AV_L_TRG,
        APPSIG_SIGNAL_ACT_SET_MTR_WHL_AV_R_PLS,
        APPSIG_SIGNAL_ACT_SET_MTR_WHL_AV_R_SPD,
        APPSIG_SIGNAL_ACT_SET_MTR_WHL_AV_R_TRG,
        APPSIG_SIGNAL_ACT_GET_MTR_XL_PLS,
        APPSIG_SIGNAL_ACT_GET_MTR_XL_SPD,
        APPSIG_SIGNAL_ACT_GET_MTR_XL_TRG,
        APPSIG_SIGNAL_ACT_GET_MTR_XR_PLS,
        APPSIG_SIGNAL_ACT_GET_MTR_XR_SPD,
        APPSIG_SIGNAL_ACT_GET_MTR_XR_TRG,
        APPSIG_SIGNAL_ACT_GET_MTR_Y_PLS,
        APPSIG_SIGNAL_ACT_GET_MTR_Y_SPD,
        APPSIG_SIGNAL_ACT_GET_MTR_Y_TRG,
        APPSIG_SIGNAL_ACT_GET_MTR_Z_PLS,
        APPSIG_SIGNAL_ACT_GET_MTR_Z_SPD,
        APPSIG_SIGNAL_ACT_GET_MTR_Z_TRG,
        APPSIG_SIGNAL_ACT_GET_MTR_HD_KNF_PLS,
        APPSIG_SIGNAL_ACT_GET_MTR_HD_KNF_SPD,
        APPSIG_SIGNAL_ACT_GET_MTR_HD_KNF_TRG,
        APPSIG_SIGNAL_ACT_GET_MTR_HD_CNTR_KNF_PLS,
        APPSIG_SIGNAL_ACT_GET_MTR_HD_CNTR_KNF_SPD,
        APPSIG_SIGNAL_ACT_GET_MTR_HD_CNTR_KNF_TRG,
        APPSIG_SIGNAL_ACT_GET_MTR_HD_HOLD_PLS,
        APPSIG_SIGNAL_ACT_GET_MTR_HD_HOLD_SPD,
        APPSIG_SIGNAL_ACT_GET_MTR_HD_HOLD_TRG,
        APPSIG_SIGNAL_ACT_GET_MTR_WHL_AV_L_PLS,
        APPSIG_SIGNAL_ACT_GET_MTR_WHL_AV_L_SPD,
        APPSIG_SIGNAL_ACT_GET_MTR_WHL_AV_L_TRG,
        APPSIG_SIGNAL_ACT_GET_MTR_WHL_AV_R_PLS,
        APPSIG_SIGNAL_ACT_GET_MTR_WHL_AV_R_SPD,
        APPSIG_SIGNAL_ACT_GET_MTR_WHL_AV_R_TRG,
        APPSIG_SIGNAL_ACT_GET_PWR_MTR_XL_RLY,
        APPSIG_SIGNAL_ACT_GET_PWR_MTR_XR_RLY,
        APPSIG_SIGNAL_ACT_GET_PWR_MTR_Y_RLY,
        APPSIG_SIGNAL_ACT_GET_PWR_MTR_Z_RLY,
        APPSIG_SIGNAL_ACT_GET_PWR_WHL_AV_L_RLY,
        APPSIG_SIGNAL_ACT_GET_PWR_WHL_AV_R_RLY,
        APPSIG_SIGNAL_ACT_GET_PWR_MTR_HD_KNF_RLY,
        APPSIG_SIGNAL_ACT_GET_PWR_MTR_HD_CNTR_KNF_RLY,
        APPSIG_SIGNAL_ACT_GET_PWR_MTR_HD_HOLD_RLY,
        APPSIG_SIGNAL_ACT_CTRL_MTR_XL_PLS,
        APPSIG_SIGNAL_ACT_CTRL_MTR_XL_SPD,
        APPSIG_SIGNAL_ACT_CTRL_MTR_XL_TRG,
        APPSIG_SIGNAL_ACT_CTRL_MTR_XR_PLS,
        APPSIG_SIGNAL_ACT_CTRL_MTR_XR_SPD,
        APPSIG_SIGNAL_ACT_CTRL_MTR_XR_TRG,
        APPSIG_SIGNAL_ACT_CTRL_MTR_Y_PLS,
        APPSIG_SIGNAL_ACT_CTRL_MTR_Y_SPD,
        APPSIG_SIGNAL_ACT_CTRL_MTR_Y_TRG,
        APPSIG_SIGNAL_ACT_CTRL_MTR_Z_PLS,
        APPSIG_SIGNAL_ACT_CTRL_MTR_Z_SPD,
        APPSIG_SIGNAL_ACT_CTRL_MTR_Z_TRG,
        APPSIG_SIGNAL_ACT_CTRL_MTR_HD_KNF_PLS,
        APPSIG_SIGNAL_ACT_CTRL_MTR_HD_KNF_SPD,
        APPSIG_SIGNAL_ACT_CTRL_MTR_HD_KNF_TRG,
        APPSIG_SIGNAL_ACT_CTRL_MTR_HD_CNTR_KNF_PLS,
        APPSIG_SIGNAL_ACT_CTRL_MTR_HD_CNTR_KNF_SPD,
        APPSIG_SIGNAL_ACT_CTRL_MTR_HD_CNTR_KNF_TRG,
        APPSIG_SIGNAL_ACT_CTRL_MTR_HD_HOLD_PLS,
        APPSIG_SIGNAL_ACT_CTRL_MTR_HD_HOLD_SPD,
        APPSIG_SIGNAL_ACT_CTRL_MTR_HD_HOLD_TRG,
        APPSIG_SIGNAL_ACT_CTRL_MTR_WHL_AV_L_PLS,
        APPSIG_SIGNAL_ACT_CTRL_MTR_WHL_AV_L_SPD,
        APPSIG_SIGNAL_ACT_CTRL_MTR_WHL_AV_L_TRG,
        APPSIG_SIGNAL_ACT_CTRL_MTR_WHL_AV_R_PLS,
        APPSIG_SIGNAL_ACT_CTRL_MTR_WHL_AV_R_SPD,
        APPSIG_SIGNAL_ACT_CTRL_MTR_WHL_AV_R_TRG,
        APPSIG_SIGNAL_PRM_FLAG_PARAM_SEND_OK,
        APPSIG_SIGNAL_PRM_GTRY_PULSE_ITER_MAX,
        APPSIG_SIGNAL_PRM_SYS_OPT_SNS_ECDR_XL,
        APPSIG_SIGNAL_PRM_SYS_OPT_SNS_ECDR_XR,
        APPSIG_SIGNAL_PRM_SYS_OPT_SNS_ECDR_Y,
        APPSIG_SIGNAL_PRM_SYS_OPT_SNS_ECDR_Z,
        APPSIG_SIGNAL_PRM_SYS_MACHINE_ID,
        APPSIG_SIGNAL_PRM_GTRY_X_RMP_CTRL_KFACTOR,
        APPSIG_SIGNAL_PRM_GTRY_X_RMP_CTRL_SLOP_SPD,
        APPSIG_SIGNAL_PRM_GTRY_X_RMP_CTRL_NB_STEP,
        APPSIG_SIGNAL_PRM_GTRY_X_SPD_MAX,
        APPSIG_SIGNAL_PRM_GTRY_X_SPD_MIN,
        APPSIG_SIGNAL_PRM_GTRY_Y_RMP_CTRL_KFACTOR,
        APPSIG_SIGNAL_PRM_GTRY_Y_RMP_CTRL_SLOP_SPD,
        APPSIG_SIGNAL_PRM_GTRY_Y_RMP_CTRL_NB_STEP,
        APPSIG_SIGNAL_PRM_GTRY_Y_SPD_MAX,
        APPSIG_SIGNAL_PRM_GTRY_Y_SPD_MIN,
        APPSIG_SIGNAL_PRM_GTRY_Z_RMP_CTRL_KFACTOR,
        APPSIG_SIGNAL_PRM_GTRY_Z_RMP_CTRL_SLOP_SPD,
        APPSIG_SIGNAL_PRM_GTRY_Z_RMP_CTRL_NB_STEP,
        APPSIG_SIGNAL_PRM_GTRY_Z_SPD_MAX,
        APPSIG_SIGNAL_PRM_GTRY_Z_SPD_MIN,
        APPSIG_SIGNAL_PRM_GTRY_ALGO_CPTE_TYPE,
        APPSIG_SIGNAL_PRM_GTRY_CALIB_TYPE,
        APPSIG_SIGNAL_PRM_GTRY_SENDITER_TYPE,
        APPSIG_SIGNAL_PRM_GTRY_AXE_X_PULSE_PER_MM,
        APPSIG_SIGNAL_PRM_GTRY_AXE_Y_PULSE_PER_MM,
        APPSIG_SIGNAL_PRM_GTRY_AXE_Z_PULSE_PER_MM,
        APPSIG_SIGNAL_PRM_GTRY_AXE_X_LEN,
        APPSIG_SIGNAL_PRM_GTRY_AXE_Y_LEN,
        APPSIG_SIGNAL_PRM_GTRY_AXE_Z_LEN,
        APPSIG_SIGNAL_PRM_GTRY_AXE_X_MIN_SPEED,
        APPSIG_SIGNAL_PRM_GTRY_AXE_Y_MIN_SPEED,
        APPSIG_SIGNAL_PRM_GTRY_AXE_Z_MIN_SPEED,
        APPSIG_SIGNAL_PRM_GTRY_X_CALIB_OFFSET,
        APPSIG_SIGNAL_PRM_GTRY_Y_CALIB_OFFSET,
        APPSIG_SIGNAL_PRM_GTRY_Z_CALIB_OFFSET,
        APPSIG_SIGNAL_PRM_GTRY_AXE_X_SAFE_HEIGHT,
        APPSIG_SIGNAL_PRM_GTRY_AXE_Y_SAFE_HEIGHT,
        APPSIG_SIGNAL_PRM_GTRY_AXE_Z_SAFE_HEIGHT,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_XL_OFFSET,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_XL_GAIN,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_XR_OFFSET,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_XR_GAIN,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_Y_OFFSET,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_Y_GAIN,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_Z_OFFSET,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_Z_GAIN,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_KNF_OFFSET,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_KNF_GAIN,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_CNTR_KNF_OFFSET,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_CNTR_KNF_GAIN,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_HOLD_KNF_OFFSET,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_HOLD_KNF_GAIN,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_WHL_AV_L_OFFSET,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_WHL_AV_L_GAIN,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_WHL_AV_R_OFFSET,
        APPSIG_SIGNAL_PRM_SNSCAL_ECDR_WHL_AV_R_GAIN,
        APPSIG_SIGNAL_LGC_CMD_CALIB_ID,
        APPSIG_SIGNAL_LGC_CMD_CALIB_REQ_STATE,
        APPSIG_SIGNAL_LGC_CMD_CALIB_CURR_FEEDBACK,
        APPSIG_SIGNAL_LGC_CMD_CALIB_PLS,
        APPSIG_SIGNAL_LGC_CMD_CALIB_SPD,
        APPSIG_SIGNAL_LGC_CMD_REARMAMENT_AGID,
        APPSIG_SIGNAL_LGC_CMD_REARMAMENT_TYPE,
        APPSIG_SIGNAL_LGC_CMD_REARMAMENT_STATE,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_POS_X,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_POS_Y,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_POS_Z,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_POS_RAYON,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_POS_THETHA,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_POS_PHI,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_STEP_X,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_STEP_Y,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_STEP_Z,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_DIR_X,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_DIR_Y,
        APPSIG_SIGNAL_LGC_GTRY_CMD_SIG_DIR_Z,
        APPSIG_SIGNAL_LGC_GTRY_FSM_STS,
        APPSIG_SIGNAL_LGC_GTRY_FSM_CALIB,
        APPSIG_SIGNAL_LGC_GTRY_FSM_CLB_AXE_X,
        APPSIG_SIGNAL_LGC_GTRY_FSM_CLB_AXE_Y,
        APPSIG_SIGNAL_LGC_GTRY_FSM_CLB_AXE_Z,
        APPSIG_SIGNAL_LGC_GTRY_FSM_OPE,
        APPSIG_SIGNAL_LGC_GTRY_FSM_OPE_CMD_PRCSS,
        APPSIG_SIGNAL_LGC_HC_CMD_CNTR_KNF_POS_SPEED,
        APPSIG_SIGNAL_LGC_GTRY_AXE_X_POSITION,
        APPSIG_SIGNAL_LGC_GTRY_AXE_Y_POSITION,
        APPSIG_SIGNAL_LGC_GTRY_AXE_Z_POSITION,
        APPSIG_SIGNAL_LGC_GTRY_ALGO_COMPUTE_TIME,
        APPSIG_SIGNAL_LGC_HC_CMD_KNIFE_POS_ID,
        APPSIG_SIGNAL_LGC_HC_CMD_KNIFE_POS_X,
        APPSIG_SIGNAL_LGC_HC_CMD_KNIFE_POS_Y,
        APPSIG_SIGNAL_LGC_HC_CMD_KNF_POS_SPEED,
        APPSIG_SIGNAL_LGC_HC_FB_AXE_X_POS,
        APPSIG_SIGNAL_LGC_HC_FB_AXE_Y_POS,
        APPSIG_SIGNAL_LGC_HC_FB_ALPHA_B_ANGLE,
        APPSIG_SIGNAL_LGC_HC_FB_ALPHA_C_ANGLE,
        APPSIG_SIGNAL_LGC_HC_FSM_STS,
        APPSIG_SIGNAL_LGC_HC_FSM_OPE_STS,
        APPSIG_SIGNAL_LGC_HC_FSM_CALIB,
        APPSIG_SIGNAL_LGC_MOT_CMD_WHL_AVL_DIR,
        APPSIG_SIGNAL_LGC_MOT_CMD_WHL_AVR_DIR,
        APPSIG_SIGNAL_LGC_MOT_CMD_WHL_AVL_DIR_SPD,
        APPSIG_SIGNAL_LGC_MOT_CMD_WHL_AVR_DIR_SPD,
        APPSIG_SIGNAL_LGC_MOT_CMD_WHL_ARL_PROP_SPD,
        APPSIG_SIGNAL_LGC_MOT_CMD_WHL_ARL_PROP_MODE,
        APPSIG_SIGNAL_LGC_MOT_CMD_WHL_ARR_PROP_SPD,
        APPSIG_SIGNAL_LGC_MOT_CMD_WHL_ARR_PROP_MODE,
        APPSIG_SIGNAL_LGC_MOT_FB_WHL_AVL_DIR_POS,
        APPSIG_SIGNAL_LGC_MOT_FB_WHL_AVR_DIR_POS,
        APPSIG_SIGNAL_LGC_MOT_FB_WHL_ARL_PROP,
        APPSIG_SIGNAL_LGC_MOT_FB_WHL_ARR_PROP,
        APPSIG_SIGNAL_LGC_MOT_FSM_STS,
        APPSIG_SIGNAL_LGC_MOT_FSM_CALIB,
        APPSIG_SIGNAL_CL42T_MTR_1_STATE,
        APPSIG_SIGNAL_CL42T_MTR_2_STATE,
        APPSIG_SIGNAL_CL42T_MTR_3_STATE,
        APPSIG_SIGNAL_CL42T_MTR_4_STATE,
        APPSIG_SIGNAL_CL42T_MTR_5_STATE,
        APPSIG_SIGNAL_CL42T_MTR_6_STATE,
        APPSIG_SIGNAL_CL42T_MTR_7_STATE,
        APPSIG_SIGNAL_CL42T_MTR_8_STATE,
        APPSIG_SIGNAL_CL42T_MTR_9_STATE,
        APPSIG_SIGNAL_CL42T_MTR_10_STATE,
        APPSIG_SIGNAL_CL42T_MTR_1_CW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_2_CW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_3_CW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_4_CW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_5_CW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_6_CW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_7_CW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_8_CW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_9_CW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_10_CW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_1_CCW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_2_CCW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_3_CCW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_4_CCW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_5_CCW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_6_CCW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_7_CCW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_8_CCW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_9_CCW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_10_CCW_ENDSTOP,
        APPSIG_SIGNAL_CL42T_MTR_1_DIRECTION,
        APPSIG_SIGNAL_CL42T_MTR_2_DIRECTION,
        APPSIG_SIGNAL_CL42T_MTR_3_DIRECTION,
        APPSIG_SIGNAL_CL42T_MTR_4_DIRECTION,
        APPSIG_SIGNAL_CL42T_MTR_5_DIRECTION,
        APPSIG_SIGNAL_CL42T_MTR_6_DIRECTION,
        APPSIG_SIGNAL_CL42T_MTR_7_DIRECTION,
        APPSIG_SIGNAL_CL42T_MTR_8_DIRECTION,
        APPSIG_SIGNAL_CL42T_MTR_9_DIRECTION,
        APPSIG_SIGNAL_CL42T_MTR_10_DIRECTION,
        APPSIG_SIGNAL_CL42T_MTR_1_DEADTIME,
        APPSIG_SIGNAL_CL42T_MTR_2_DEADTIME,
        APPSIG_SIGNAL_CL42T_MTR_3_DEADTIME,
        APPSIG_SIGNAL_CL42T_MTR_4_DEADTIME,
        APPSIG_SIGNAL_CL42T_MTR_5_DEADTIME,
        APPSIG_SIGNAL_CL42T_MTR_6_DEADTIME,
        APPSIG_SIGNAL_CL42T_MTR_7_DEADTIME,
        APPSIG_SIGNAL_CL42T_MTR_8_DEADTIME,
        APPSIG_SIGNAL_CL42T_MTR_9_DEADTIME,
        APPSIG_SIGNAL_CL42T_MTR_10_DEADTIME,
        APPSIG_SIGNAL_CL42T_MTR_1_HEALTH,
        APPSIG_SIGNAL_CL42T_MTR_2_HEALTH,
        APPSIG_SIGNAL_CL42T_MTR_3_HEALTH,
        APPSIG_SIGNAL_CL42T_MTR_4_HEALTH,
        APPSIG_SIGNAL_CL42T_MTR_5_HEALTH,
        APPSIG_SIGNAL_CL42T_MTR_6_HEALTH,
        APPSIG_SIGNAL_CL42T_MTR_7_HEALTH,
        APPSIG_SIGNAL_CL42T_MTR_8_HEALTH,
        APPSIG_SIGNAL_CL42T_MTR_9_HEALTH,
        APPSIG_SIGNAL_CL42T_MTR_10_HEALTH,
    
        APPSIG_SIGNAL_NB,
    } t_eAPPSIG_Signal;

    /**
    * @brief message serial available.
    */
    typedef enum
    {
    
        APPSIG_SRL_MSG_NB,
    } t_eAPPSIG_SrlMsgList;

    /**
    * @brief message can available.
    */
    typedef enum
    {
        APPSIG_CAN_MSG_APPLICATIONINFO0 = 0,
        APPSIG_CAN_MSG_APPLICATIONINFO1,
        APPSIG_CAN_MSG_APPLICATIONINFO2,
        APPSIG_CAN_MSG_APPLICATIONDIAGNOSTIC0,
        APPSIG_CAN_MSG_APPLICATIONDIAGNOSTIC1,
        APPSIG_CAN_MSG_APPLICATIONDIAGNOSTIC2,
        APPSIG_CAN_MSG_APPLICATIONDIAGNOSTICECUSAFETY,
        APPSIG_CAN_MSG_APPACT_CTRL_MTR_XL,
        APPSIG_CAN_MSG_APPACT_CTRL_MTR_XR,
        APPSIG_CAN_MSG_APPACT_CTRL_MTR_Y,
        APPSIG_CAN_MSG_APPACT_CTRL_MTR_Z,
        APPSIG_CAN_MSG_APPACT_CTRL_MTR_HD_KNF,
        APPSIG_CAN_MSG_APPACT_CTRL_MTR_HD_CNTR_KNF,
        APPSIG_CAN_MSG_APPACT_CTRL_MTR_HD_HOLD,
        APPSIG_CAN_MSG_APPACT_CTRL_MTR_WHL_AV_L,
        APPSIG_CAN_MSG_APPACT_CTRL_MTR_WHL_AV_R,
        APPSIG_CAN_MSG_APPACT_SET_MTR_XL,
        APPSIG_CAN_MSG_APPACT_SET_MTR_XR,
        APPSIG_CAN_MSG_APPACT_SET_MTR_Y,
        APPSIG_CAN_MSG_APPACT_SET_MTR_Z,
        APPSIG_CAN_MSG_APPACT_SET_MTR_HD_KNF,
        APPSIG_CAN_MSG_APPACT_SET_MTR_HD_CNTR_KNF,
        APPSIG_CAN_MSG_APPACT_SET_MTR_HD_HOLD,
        APPSIG_CAN_MSG_APPACT_SET_MTR_WHL_AV_L,
        APPSIG_CAN_MSG_APPACT_SET_MTR_WHL_AV_R,
        APPSIG_CAN_MSG_APPACT_GET_MTR_XL,
        APPSIG_CAN_MSG_APPACT_GET_MTR_XR,
        APPSIG_CAN_MSG_APPACT_GET_MTR_Y,
        APPSIG_CAN_MSG_APPACT_GET_MTR_Z,
        APPSIG_CAN_MSG_APPACT_GET_MTR_HD_KNF,
        APPSIG_CAN_MSG_APPACT_GET_MTR_HD_CNTR_KNF,
        APPSIG_CAN_MSG_APPACT_GET_MTR_HD_HOLD,
        APPSIG_CAN_MSG_APPACT_GET_MTR_WHL_AV_L,
        APPSIG_CAN_MSG_APPACT_GET_MTR_WHL_AV_R,
        APPSIG_CAN_MSG_APPACT_GET_ACT_PWR_MTR,
        APPSIG_CAN_MSG_APPSNS_GET_ECDR_GTRY_XL_XR,
        APPSIG_CAN_MSG_APPSNS_GET_ECDR_GTRY_Y_Z,
        APPSIG_CAN_MSG_APPSNS_GET_TRQ_GTRY_XL_XR_Y_Z,
        APPSIG_CAN_MSG_APPSNS_GET_TRQ_WHEEL_DIRECTION,
        APPSIG_CAN_MSG_APPSNS_GET_TRQ_HEAD_KNIFE,
        APPSIG_CAN_MSG_PRM_SEND_STATUS_ECU_0,
        APPSIG_CAN_MSG_PRM_SEND_STATUS_ECU_1,
        APPSIG_CAN_MSG_PRM_SEND_STATUS_ECU_2,
        APPSIG_CAN_MSG_PRM_GTRY_X_RAMP_CTRL,
        APPSIG_CAN_MSG_PRM_GTRY_Y_RAMP_CTRL,
        APPSIG_CAN_MSG_PRM_GTRY_Z_RAMP_CTRL,
        APPSIG_CAN_MSG_PRM_GTRY_SPD_CFG1,
        APPSIG_CAN_MSG_PRM_GTRY_SPD_CFG_2,
        APPSIG_CAN_MSG_PRM_GTRY_SPD_CFG_3,
        APPSIG_CAN_MSG_PRM_LGC_GTRY_CMD_SPHERIC,
        APPSIG_CAN_MSG_PRM_GTRY_PARAM_1,
        APPSIG_CAN_MSG_PRM_GTRY_PARAM_2,
        APPSIG_CAN_MSG_PRM_GTRY_PARAM_3,
        APPSIG_CAN_MSG_PRM_GTRY_PARAM_4,
        APPSIG_CAN_MSG_PRM_GTRY_PARAM_SAFE_HEIGHT,
        APPSIG_CAN_MSG_LGC_CL42T_MOTORS_INFO_GTRY,
        APPSIG_CAN_MSG_LGC_CL42T_MOTORS_INFO_HEAD_GTRY,
        APPSIG_CAN_MSG_LGC_CL42T_MOTORS_INFO_MOTION,
        APPSIG_CAN_MSG_LGC_REARMAMENT_CMD,
        APPSIG_CAN_MSG_LGC_GTRY_CMD_POSITION,
        APPSIG_CAN_MSG_LGC_GTRY_CMD_STEPS,
        APPSIG_CAN_MSG_LGC_GTRY_POSITION,
        APPSIG_CAN_MSG_LGC_GTRY_DEBUG_FSM,
        APPSIG_CAN_MSG_LGC_HC_CMD_CALIBRATION,
        APPSIG_CAN_MSG_LGC_HC_CMD_POSITION,
        APPSIG_CAN_MSG_LGC_HC_FEEDBACK_POS,
        APPSIG_CAN_MSG_LGC_MOT_CMD_CALIBRATION,
        APPSIG_CAN_MSG_LGC_MOT_CMD_WHL_AV_POSITION,
        APPSIG_CAN_MSG_LGC_MOT_CMD_WHL_AR_PROPULSION,
        APPSIG_CAN_MSG_LGC_MOT_DEBUG_FSM,
        APPSIG_CAN_MSG_LGC_MOT_FB_DIR_PROPR,
    
        APPSIG_CAN_MSG_NB,
    } t_eAPPSIG_CanMsgList;

    /* CAUTION : Automatic generated code section for Enum: End */
	//-----------------------------ENUM TYPES-----------------------------//

	/* CAUTION : Automatic generated code section for Structure: Start */

	/* CAUTION : Automatic generated code section for Structure: End */
	//-----------------------------STRUCT TYPES---------------------------//

	/* CAUTION : Automatic generated code section : Start */

	/* CAUTION : Automatic generated code section : End */
	//-----------------------------TYPEDEF TYPES---------------------------//
    // ********************************************************************
    // *                      Prototypes
    // ********************************************************************
    
    // ********************************************************************
    // *                      Variables
    // ********************************************************************
    
    

    //********************************************************************************
    //                      Public functions - Prototyupes
    //********************************************************************************

#endif // APPSDM_CONFIGPUBLIC_H_INCLUDED           
//************************************************************************************
// End of File
//************************************************************************************

/**
 *
 *	@brief
 *	@note   
 *
 *
 *	@params[in] 
 *	@params[out]
 *	 
 *
 *
 */
